[package]
name = "gh-pages-publish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
cmd_lib = "1.1"
clap = {version = "3", features = ["derive"]}
which = "4.2"
