name: Release
on: 
  push:
    tags: 
      - '*'

jobs:
  build_artifacts:
    name: Build artifacts for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          linux,
          macos,
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/gh-pages-publish-linux
            asset_name: gh-pages-publish-linux
          - name: macos
            os: macos-latest
            artifact_name: target/release/gh-pages-publish-macos
            asset_name: gh-pages-publish-macos

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Strip binaries
        run: strip target/release/gh-pages-publish

      - name: Rename artifacts
        run: mv target/release/gh-pages-publish target/release/${{ matrix.asset_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

  deploy_artifacts:
    name: Create release
    needs: build_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gh-pages-publish-*/*"
          token: ${{ secrets.GITHUB_TOKEN }}
